"""Job-role catalog: the roles the classifier is trained on and the job
profiles used for role recommendations.

``bullets`` are experience-bullet templates used by the synthetic data
generator; ``{s}`` is replaced with a skill from the candidate being generated.
"""
from __future__ import annotations

ROLES: list[dict] = [
    {
        "id": "data-scientist",
        "title": "Data Scientist",
        "description": "Uses statistics and machine learning to turn large datasets into predictive models and business insight.",
        "responsibilities": [
            "Build, validate and deploy predictive models",
            "Perform exploratory data analysis and feature engineering",
            "Design experiments and A/B tests and communicate findings to stakeholders",
        ],
        "core": ["Python", "Machine Learning", "Statistics", "Scikit-learn", "Pandas", "SQL", "Feature Engineering"],
        "secondary": ["Deep Learning", "NumPy", "Data Visualization", "Jupyter", "TensorFlow", "PyTorch", "R", "NLP", "Gradient Boosting", "Apache Spark", "Tableau"],
        "titles": ["Data Scientist", "Junior Data Scientist", "Senior Data Scientist", "Applied Scientist", "Data Science Intern"],
        "edu_fields": ["Data Science", "Statistics", "Computer Science", "Mathematics", "Artificial Intelligence"],
        "certs": ["IBM Data Science Professional Certificate", "Coursera Machine Learning Specialization", "Google Data Analytics Certificate"],
        "adjacent": ["machine-learning-engineer", "data-analyst"],
        "min_years": 2,
        "bullets": [
            "Developed a customer churn prediction model using {s}, improving retention targeting precision by {pct}%",
            "Performed exploratory data analysis on {n}M+ records with {s} to uncover drivers of revenue growth",
            "Designed and analysed A/B experiments, translating statistical results into product decisions",
            "Engineered {n}+ features and tuned models with cross-validation, lifting AUC from 0.7{a} to 0.8{b}",
            "Built demand forecasting models in {s} that reduced inventory cost by {pct}%",
            "Presented model insights to leadership and partnered with product teams to act on them",
            "Automated reporting notebooks using {s}, saving the team {n} hours per week",
        ],
    },
    {
        "id": "machine-learning-engineer",
        "title": "Machine Learning Engineer",
        "description": "Designs, trains and productionises machine learning systems and the infrastructure that serves them at scale.",
        "responsibilities": [
            "Train and optimise deep learning and ML models",
            "Deploy models as scalable services with monitoring and CI/CD",
            "Build data and feature pipelines for training and inference",
        ],
        "core": ["Python", "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "MLOps", "Docker"],
        "secondary": ["Scikit-learn", "NLP", "Computer Vision", "LLMs", "Kubernetes", "AWS", "Git", "CI/CD", "REST APIs", "FastAPI", "NumPy", "Apache Spark", "Keras"],
        "titles": ["Machine Learning Engineer", "ML Engineer", "Senior Machine Learning Engineer", "AI Engineer", "Deep Learning Engineer"],
        "edu_fields": ["Computer Science", "Artificial Intelligence", "Machine Learning", "Electrical Engineering"],
        "certs": ["TensorFlow Developer Certificate", "AWS Certified Machine Learning Specialty", "DeepLearning.AI Deep Learning Specialization"],
        "adjacent": ["data-scientist", "backend-developer"],
        "min_years": 3,
        "bullets": [
            "Trained and deployed {s} models serving {n}K+ requests per day with p95 latency under {n2}ms",
            "Built an end-to-end MLOps pipeline for retraining, versioning and monitoring models in production",
            "Fine-tuned transformer models for text classification, improving F1 by {pct}% over the baseline",
            "Containerised inference services with {s} and automated rollouts through CI/CD",
            "Optimised model inference using quantisation and batching, cutting GPU cost by {pct}%",
            "Implemented computer vision and NLP prototypes and shipped them into customer-facing features",
            "Created reusable feature pipelines and model evaluation tooling used by {n} data scientists",
        ],
    },
    {
        "id": "data-analyst",
        "title": "Data Analyst",
        "description": "Collects, cleans and analyses data and builds dashboards and reports that support business decisions.",
        "responsibilities": [
            "Write SQL queries to extract and transform data",
            "Build interactive dashboards and recurring reports",
            "Analyse trends and present actionable insights to business teams",
        ],
        "core": ["SQL", "Excel", "Data Analysis", "Data Visualization", "Tableau", "Power BI", "Business Intelligence"],
        "secondary": ["Python", "Pandas", "Statistics", "Product Analytics", "Communication", "Looker", "Data Warehousing", "R", "Stakeholder Management", "Documentation"],
        "titles": ["Data Analyst", "Junior Data Analyst", "Senior Data Analyst", "Business Data Analyst", "Reporting Analyst"],
        "edu_fields": ["Statistics", "Economics", "Business Analytics", "Computer Science", "Mathematics"],
        "certs": ["Google Data Analytics Professional Certificate", "Microsoft Power BI Data Analyst Associate", "Tableau Desktop Specialist"],
        "adjacent": ["data-scientist", "business-analyst"],
        "min_years": 1,
        "bullets": [
            "Built {n}+ interactive dashboards in {s} used daily by sales and operations leaders",
            "Wrote optimised SQL queries across {n} data sources to produce weekly KPI reports",
            "Cleaned and consolidated datasets with {s}, reducing manual reporting effort by {pct}%",
            "Identified a {pct}% drop in conversion through funnel analysis and recommended fixes",
            "Automated monthly reports with {s}, saving {n} hours per month",
            "Presented trend analysis to stakeholders and tracked the impact of resulting decisions",
            "Defined metrics and a single source of truth for marketing performance reporting",
        ],
    },
    {
        "id": "data-engineer",
        "title": "Data Engineer",
        "description": "Builds and maintains reliable data pipelines, warehouses and platforms that make data available for analytics and ML.",
        "responsibilities": [
            "Design and operate batch and streaming ETL pipelines",
            "Model and maintain the data warehouse / lakehouse",
            "Ensure data quality, observability and cost efficiency",
        ],
        "core": ["Python", "SQL", "ETL", "Apache Spark", "Airflow", "Data Warehousing", "Kafka"],
        "secondary": ["AWS", "Snowflake", "BigQuery", "Redshift", "Databricks", "Hadoop", "dbt", "Docker", "Git", "PostgreSQL", "Azure", "Terraform", "Scala"],
        "titles": ["Data Engineer", "Junior Data Engineer", "Senior Data Engineer", "Big Data Engineer", "Analytics Engineer"],
        "edu_fields": ["Computer Science", "Information Technology", "Software Engineering", "Data Engineering"],
        "certs": ["Google Professional Data Engineer", "AWS Certified Data Analytics Specialty", "Databricks Certified Data Engineer Associate"],
        "adjacent": ["backend-developer", "data-analyst"],
        "min_years": 3,
        "bullets": [
            "Designed {s} pipelines processing {n}TB of data daily with automated quality checks",
            "Migrated legacy batch jobs to a streaming architecture, cutting data latency from hours to minutes",
            "Orchestrated {n}+ workflows in {s} with retries, alerting and SLAs",
            "Modelled a dimensional data warehouse that reduced analyst query time by {pct}%",
            "Optimised {s} jobs and storage layout, lowering monthly compute cost by {pct}%",
            "Implemented data quality monitoring and lineage tracking across {n} critical datasets",
            "Collaborated with data scientists to ship reliable feature tables and reporting marts",
        ],
    },
    {
        "id": "backend-developer",
        "title": "Backend Developer",
        "description": "Designs and builds server-side applications, APIs and databases that are secure, scalable and maintainable.",
        "responsibilities": [
            "Design and implement RESTful APIs and microservices",
            "Model data and optimise database queries",
            "Write tested, documented, production-grade code",
        ],
        "core": ["REST APIs", "SQL", "Microservices", "Git", "Database Design", "Data Structures & Algorithms", "OOP"],
        "secondary": ["Java", "Spring Boot", "Python", "Django", "Node.js", "PostgreSQL", "MySQL", "Docker", "Redis", "AWS", "Message Queues", "Unit Testing", "System Design", "Authentication", "Kubernetes", "FastAPI", "Flask", "MongoDB"],
        "titles": ["Backend Developer", "Software Engineer", "Senior Backend Engineer", "Java Developer", "Python Developer", "Backend Engineer"],
        "edu_fields": ["Computer Science", "Information Technology", "Software Engineering", "Computer Engineering"],
        "certs": ["Oracle Certified Professional Java SE", "AWS Certified Developer Associate", "MongoDB Developer Certification"],
        "adjacent": ["full-stack-developer", "devops-engineer"],
        "min_years": 2,
        "bullets": [
            "Designed and shipped {n}+ RESTful APIs with {s}, serving {n2}K requests per minute",
            "Decomposed a monolith into microservices, improving deployment frequency by {pct}%",
            "Optimised slow {s} queries and added caching, reducing average response time by {pct}%",
            "Implemented authentication, rate limiting and role-based access control for public APIs",
            "Wrote unit and integration tests achieving {pct}% coverage across core services",
            "Integrated asynchronous processing with message queues to handle traffic spikes reliably",
            "Reviewed code, mentored junior developers and documented API contracts using OpenAPI",
        ],
    },
    {
        "id": "frontend-developer",
        "title": "Frontend Developer",
        "description": "Builds responsive, accessible and high-performance user interfaces for web applications.",
        "responsibilities": [
            "Implement pixel-perfect, responsive UIs from design specs",
            "Build reusable component libraries and manage client state",
            "Optimise page performance and ensure accessibility",
        ],
        "core": ["JavaScript", "HTML", "CSS", "React", "Responsive Design", "TypeScript", "Git"],
        "secondary": ["Redux", "Next.js", "Tailwind CSS", "Webpack", "Jest", "Web Accessibility", "REST APIs", "Figma", "Angular", "Vue.js", "Bootstrap", "GraphQL", "Cypress"],
        "titles": ["Frontend Developer", "Front-End Engineer", "UI Developer", "Senior Frontend Engineer", "React Developer"],
        "edu_fields": ["Computer Science", "Information Technology", "Web Design", "Software Engineering"],
        "certs": ["Meta Front-End Developer Professional Certificate", "freeCodeCamp Responsive Web Design", "W3C Front-End Web Developer"],
        "adjacent": ["full-stack-developer", "mobile-app-developer"],
        "min_years": 2,
        "bullets": [
            "Built a reusable component library in {s} adopted across {n} product teams",
            "Improved Lighthouse performance score from {n2} to 9{a} through code splitting and lazy loading",
            "Delivered responsive, cross-browser interfaces from Figma designs using {s}",
            "Implemented accessible UI patterns (WCAG 2.1) and keyboard navigation for all forms",
            "Integrated REST and GraphQL APIs and managed complex state with {s}",
            "Wrote component and end-to-end tests that cut UI regressions by {pct}%",
            "Collaborated with designers and backend engineers to ship features every sprint",
        ],
    },
    {
        "id": "full-stack-developer",
        "title": "Full Stack Developer",
        "description": "Works across the entire stack, delivering features from the database and APIs through to the user interface.",
        "responsibilities": [
            "Build end-to-end features across frontend and backend",
            "Design APIs, databases and responsive web UIs",
            "Deploy and maintain applications in the cloud",
        ],
        "core": ["JavaScript", "React", "Node.js", "REST APIs", "SQL", "HTML", "CSS", "Git"],
        "secondary": ["TypeScript", "MongoDB", "Express", "PostgreSQL", "Docker", "AWS", "Next.js", "Redux", "GraphQL", "Python", "Django", "CI/CD", "Authentication", "MySQL", "Angular"],
        "titles": ["Full Stack Developer", "Full-Stack Engineer", "Software Developer", "MERN Stack Developer", "Senior Full Stack Engineer"],
        "edu_fields": ["Computer Science", "Information Technology", "Software Engineering", "Computer Applications"],
        "certs": ["Meta Full-Stack Engineer Certificate", "AWS Certified Cloud Practitioner", "The Odin Project Full Stack Path"],
        "adjacent": ["frontend-developer", "backend-developer"],
        "min_years": 2,
        "bullets": [
            "Developed a full-stack web application with {s} that onboarded {n}K users in the first quarter",
            "Built REST APIs and database schemas and the React interfaces that consume them",
            "Implemented secure authentication and payments integration across web and API layers",
            "Set up CI/CD pipelines and deployed services to the cloud with {s}",
            "Refactored legacy pages into reusable components, reducing page load time by {pct}%",
            "Owned features end to end from requirements and design to testing and release",
            "Wrote automated tests for both client and server code to keep releases stable",
        ],
    },
    {
        "id": "devops-engineer",
        "title": "DevOps Engineer",
        "description": "Automates build, deployment and infrastructure to deliver software reliably and operate it at scale.",
        "responsibilities": [
            "Build and maintain CI/CD pipelines",
            "Provision and manage cloud infrastructure as code",
            "Monitor systems and improve reliability and incident response",
        ],
        "core": ["Docker", "Kubernetes", "CI/CD", "Terraform", "AWS", "Linux", "Jenkins"],
        "secondary": ["Git", "Configuration Management", "Monitoring", "Shell Scripting", "Python", "Azure", "GitHub Actions", "Nginx", "Networking", "SRE", "GitLab CI", "GCP"],
        "titles": ["DevOps Engineer", "Site Reliability Engineer", "Cloud Engineer", "Senior DevOps Engineer", "Platform Engineer"],
        "edu_fields": ["Computer Science", "Information Technology", "Computer Networks", "Electronics"],
        "certs": ["Certified Kubernetes Administrator (CKA)", "AWS Certified DevOps Engineer Professional", "HashiCorp Certified: Terraform Associate"],
        "adjacent": ["backend-developer", "cybersecurity-analyst"],
        "min_years": 3,
        "bullets": [
            "Built CI/CD pipelines with {s} that cut release time from days to under {n} minutes",
            "Provisioned multi-environment cloud infrastructure with {s}, eliminating configuration drift",
            "Operated Kubernetes clusters running {n}+ services with autoscaling and zero-downtime deploys",
            "Implemented monitoring and alerting with {s}, reducing mean time to recovery by {pct}%",
            "Automated server configuration and patching with scripts across {n}+ Linux hosts",
            "Reduced cloud spend by {pct}% through right-sizing, autoscaling and spot instances",
            "Led incident response and wrote post-mortems that improved reliability practices",
        ],
    },
    {
        "id": "mobile-app-developer",
        "title": "Mobile App Developer",
        "description": "Builds native and cross-platform mobile applications for Android and iOS.",
        "responsibilities": [
            "Develop and ship mobile apps to the Play Store and App Store",
            "Integrate APIs, push notifications and offline storage",
            "Profile and optimise app performance and stability",
        ],
        "core": ["Android", "Kotlin", "Mobile Development", "Firebase", "REST APIs", "Git", "Java"],
        "secondary": ["iOS", "Swift", "Flutter", "Dart", "React Native", "Unit Testing", "CI/CD", "Figma", "Appium", "OOP"],
        "titles": ["Mobile App Developer", "Android Developer", "iOS Developer", "Flutter Developer", "Senior Mobile Engineer"],
        "edu_fields": ["Computer Science", "Information Technology", "Software Engineering", "Computer Applications"],
        "certs": ["Google Associate Android Developer", "Meta React Native Specialization", "Apple Developer Academy Program"],
        "adjacent": ["frontend-developer", "full-stack-developer"],
        "min_years": 2,
        "bullets": [
            "Developed and published {n} mobile apps using {s} with a combined {n2}K+ downloads",
            "Integrated REST APIs, Firebase push notifications and offline caching",
            "Reduced app crash rate by {pct}% through profiling and memory-leak fixes",
            "Implemented MVVM architecture and dependency injection for a maintainable codebase",
            "Built pixel-perfect screens from design specs and supported multiple screen sizes",
            "Automated builds and releases to the Play Store and App Store via CI/CD",
            "Wrote unit and UI tests and responded to user reviews with rapid fixes",
        ],
    },
    {
        "id": "qa-engineer",
        "title": "QA Engineer",
        "description": "Ensures software quality through test planning, manual and automated testing, and defect management.",
        "responsibilities": [
            "Design test plans and test cases from requirements",
            "Build and maintain automated regression suites",
            "Track defects and collaborate with developers to resolve them",
        ],
        "core": ["Manual Testing", "Test Automation", "Selenium", "Jira", "Postman", "Performance Testing", "Agile"],
        "secondary": ["Java", "Python", "JUnit", "PyTest", "BDD", "Cypress", "SQL", "Appium", "CI/CD", "Jenkins", "Git", "Playwright", "TDD", "Documentation", "Communication"],
        "titles": ["QA Engineer", "Software Test Engineer", "Test Automation Engineer", "SDET", "Senior QA Analyst"],
        "edu_fields": ["Computer Science", "Information Technology", "Computer Applications", "Electronics"],
        "certs": ["ISTQB Certified Tester Foundation Level", "Certified Associate in Software Testing", "Selenium WebDriver Certification"],
        "adjacent": ["backend-developer", "business-analyst"],
        "min_years": 2,
        "bullets": [
            "Designed and executed {n}+ test cases covering functional, regression and smoke scenarios",
            "Built a {s}-based automation framework that automated {pct}% of the regression suite",
            "Logged and triaged defects in Jira, working with developers to cut escaped bugs by {pct}%",
            "Performed API testing with Postman and load testing with {s} to validate performance targets",
            "Integrated automated tests into CI/CD so every build runs regression checks",
            "Participated in sprint planning and grooming to define acceptance criteria and test coverage",
            "Mentored {n} junior testers and standardised test documentation and reporting",
        ],
    },
    {
        "id": "cybersecurity-analyst",
        "title": "Cybersecurity Analyst",
        "description": "Protects systems and data by monitoring threats, assessing vulnerabilities and responding to security incidents.",
        "responsibilities": [
            "Monitor security events and investigate alerts in the SIEM",
            "Run vulnerability assessments and penetration tests",
            "Respond to incidents and maintain security policies and compliance",
        ],
        "core": ["Cybersecurity", "SIEM", "Incident Response", "Network Security", "Penetration Testing", "Compliance", "Linux"],
        "secondary": ["Wireshark", "Nmap", "Metasploit", "OWASP", "IAM", "Cryptography", "Networking", "Python", "Shell Scripting", "Monitoring", "AWS", "Documentation"],
        "titles": ["Cybersecurity Analyst", "Security Analyst", "SOC Analyst", "Information Security Engineer", "Penetration Tester"],
        "edu_fields": ["Cyber Security", "Computer Science", "Information Technology", "Computer Networks"],
        "certs": ["CompTIA Security+", "Certified Ethical Hacker (CEH)", "CISSP Associate", "GIAC Security Essentials (GSEC)"],
        "adjacent": ["devops-engineer", "backend-developer"],
        "min_years": 2,
        "bullets": [
            "Monitored and triaged {n}+ daily security alerts in the SIEM, escalating confirmed incidents",
            "Conducted vulnerability assessments with {s} and tracked remediation to closure",
            "Led incident response for phishing and malware events, reducing time to containment by {pct}%",
            "Performed penetration tests on web applications and internal networks and reported findings to owners",
            "Hardened firewall and access policies and supported ISO 27001 and GDPR compliance audits",
            "Delivered security awareness training that reduced phishing click rates by {pct}%",
            "Wrote detection rules and runbooks to improve threat detection coverage",
        ],
    },
    {
        "id": "business-analyst",
        "title": "Business Analyst",
        "description": "Bridges business and technology teams by gathering requirements, analysing processes and defining solutions.",
        "responsibilities": [
            "Elicit and document business and functional requirements",
            "Map processes, identify gaps and recommend improvements",
            "Coordinate with stakeholders and delivery teams through the project lifecycle",
        ],
        "core": ["Requirements Gathering", "Stakeholder Management", "Process Modeling", "Gap Analysis", "Agile", "Documentation", "Jira"],
        "secondary": ["SQL", "Excel", "Power BI", "Tableau", "Project Management", "Communication", "Product Analytics", "Business Intelligence", "Leadership", "Data Analysis", "Problem Solving"],
        "titles": ["Business Analyst", "Junior Business Analyst", "Senior Business Analyst", "Functional Analyst", "Product Analyst"],
        "edu_fields": ["Business Administration", "Information Systems", "Economics", "Commerce", "Computer Science"],
        "certs": ["CBAP Certification", "PMI Professional in Business Analysis (PMI-PBA)", "Certified Scrum Product Owner"],
        "adjacent": ["data-analyst", "qa-engineer"],
        "min_years": 2,
        "bullets": [
            "Gathered and documented requirements from {n}+ stakeholders using workshops and user stories",
            "Mapped as-is and to-be business processes with BPMN, identifying {pct}% efficiency gains",
            "Ran gap analysis and cost-benefit analysis to prioritise the product backlog",
            "Facilitated sprint planning and acceptance testing with delivery teams in {s}",
            "Created BRDs, FRDs and process documentation that reduced rework between teams",
            "Analysed operational data with {s} to build the case for new features",
            "Managed stakeholder expectations and communicated project status to senior leadership",
        ],
    },
]

ROLE_BY_ID = {r["id"]: r for r in ROLES}
ROLE_BY_TITLE = {r["title"]: r for r in ROLES}


def role_profile_text(role: dict) -> str:
    """Free text describing a role (used for TF-IDF similarity)."""
    skills = role["core"] * 2 + role["secondary"]
    return " ".join([role["title"], role["description"], *role["responsibilities"], *skills])


def role_job_description(role: dict) -> str:
    """An example job description for a role (used by the UI's 'load example')."""
    lines = [
        f"We are hiring a {role['title']}.",
        "",
        role["description"],
        "",
        "Responsibilities:",
        *[f"- {r}" for r in role["responsibilities"]],
        "",
        "Requirements:",
        f"- {role['min_years']}+ years of relevant experience",
        "- Bachelor's degree in " + " / ".join(role["edu_fields"][:2]) + " or equivalent",
        "- Strong hands-on skills in " + ", ".join(role["core"]),
        "",
        "Nice to have: " + ", ".join(role["secondary"][:5]) + ".",
    ]
    return "\n".join(lines)
